//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace VocabTrainerPhoneApp.VocabTrainerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VocabTrainerServiceReference.ISchool")]
    public interface ISchool {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISchool/GetClassRooms", ReplyAction="http://tempuri.org/ISchool/GetClassRoomsResponse")]
        System.IAsyncResult BeginGetClassRooms(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Marx.Wolfgang.VocabTrainer.DataModel.BasicClassRoom> EndGetClassRooms(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISchool/GetLastDataUpdate", ReplyAction="http://tempuri.org/ISchool/GetLastDataUpdateResponse")]
        System.IAsyncResult BeginGetLastDataUpdate(System.AsyncCallback callback, object asyncState);
        
        System.DateTime EndGetLastDataUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISchool/DoWork", ReplyAction="http://tempuri.org/ISchool/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchoolChannel : VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClassRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClassRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Marx.Wolfgang.VocabTrainer.DataModel.BasicClassRoom> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Marx.Wolfgang.VocabTrainer.DataModel.BasicClassRoom>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLastDataUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLastDataUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.DateTime Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolClient : System.ServiceModel.ClientBase<VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool>, VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool {
        
        private BeginOperationDelegate onBeginGetClassRoomsDelegate;
        
        private EndOperationDelegate onEndGetClassRoomsDelegate;
        
        private System.Threading.SendOrPostCallback onGetClassRoomsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLastDataUpdateDelegate;
        
        private EndOperationDelegate onEndGetLastDataUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onGetLastDataUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SchoolClient() {
        }
        
        public SchoolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetClassRoomsCompletedEventArgs> GetClassRoomsCompleted;
        
        public event System.EventHandler<GetLastDataUpdateCompletedEventArgs> GetLastDataUpdateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool.BeginGetClassRooms(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClassRooms(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Marx.Wolfgang.VocabTrainer.DataModel.BasicClassRoom> VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool.EndGetClassRooms(System.IAsyncResult result) {
            return base.Channel.EndGetClassRooms(result);
        }
        
        private System.IAsyncResult OnBeginGetClassRooms(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool)(this)).BeginGetClassRooms(callback, asyncState);
        }
        
        private object[] OnEndGetClassRooms(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Marx.Wolfgang.VocabTrainer.DataModel.BasicClassRoom> retVal = ((VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool)(this)).EndGetClassRooms(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClassRoomsCompleted(object state) {
            if ((this.GetClassRoomsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClassRoomsCompleted(this, new GetClassRoomsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClassRoomsAsync() {
            this.GetClassRoomsAsync(null);
        }
        
        public void GetClassRoomsAsync(object userState) {
            if ((this.onBeginGetClassRoomsDelegate == null)) {
                this.onBeginGetClassRoomsDelegate = new BeginOperationDelegate(this.OnBeginGetClassRooms);
            }
            if ((this.onEndGetClassRoomsDelegate == null)) {
                this.onEndGetClassRoomsDelegate = new EndOperationDelegate(this.OnEndGetClassRooms);
            }
            if ((this.onGetClassRoomsCompletedDelegate == null)) {
                this.onGetClassRoomsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClassRoomsCompleted);
            }
            base.InvokeAsync(this.onBeginGetClassRoomsDelegate, null, this.onEndGetClassRoomsDelegate, this.onGetClassRoomsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool.BeginGetLastDataUpdate(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLastDataUpdate(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.DateTime VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool.EndGetLastDataUpdate(System.IAsyncResult result) {
            return base.Channel.EndGetLastDataUpdate(result);
        }
        
        private System.IAsyncResult OnBeginGetLastDataUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool)(this)).BeginGetLastDataUpdate(callback, asyncState);
        }
        
        private object[] OnEndGetLastDataUpdate(System.IAsyncResult result) {
            System.DateTime retVal = ((VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool)(this)).EndGetLastDataUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLastDataUpdateCompleted(object state) {
            if ((this.GetLastDataUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLastDataUpdateCompleted(this, new GetLastDataUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLastDataUpdateAsync() {
            this.GetLastDataUpdateAsync(null);
        }
        
        public void GetLastDataUpdateAsync(object userState) {
            if ((this.onBeginGetLastDataUpdateDelegate == null)) {
                this.onBeginGetLastDataUpdateDelegate = new BeginOperationDelegate(this.OnBeginGetLastDataUpdate);
            }
            if ((this.onEndGetLastDataUpdateDelegate == null)) {
                this.onEndGetLastDataUpdateDelegate = new EndOperationDelegate(this.OnEndGetLastDataUpdate);
            }
            if ((this.onGetLastDataUpdateCompletedDelegate == null)) {
                this.onGetLastDataUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastDataUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginGetLastDataUpdateDelegate, null, this.onEndGetLastDataUpdateDelegate, this.onGetLastDataUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool CreateChannel() {
            return new SchoolClientChannel(this);
        }
        
        private class SchoolClientChannel : ChannelBase<VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool>, VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool {
            
            public SchoolClientChannel(System.ServiceModel.ClientBase<VocabTrainerPhoneApp.VocabTrainerServiceReference.ISchool> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetClassRooms(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetClassRooms", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Marx.Wolfgang.VocabTrainer.DataModel.BasicClassRoom> EndGetClassRooms(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Marx.Wolfgang.VocabTrainer.DataModel.BasicClassRoom> _result = ((System.Collections.ObjectModel.ObservableCollection<Marx.Wolfgang.VocabTrainer.DataModel.BasicClassRoom>)(base.EndInvoke("GetClassRooms", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLastDataUpdate(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetLastDataUpdate", _args, callback, asyncState);
                return _result;
            }
            
            public System.DateTime EndGetLastDataUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.DateTime _result = ((System.DateTime)(base.EndInvoke("GetLastDataUpdate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
        }
    }
}
